<?

	include $_SERVER["DOCUMENT_ROOT"]."/library/db.php";


	$conn = init_sql();

	$output = array();

	$session = $_GET["session"];
    $meta = $_GET["meta"];

    if (isset($_GET["db"]) && isset($_GET["time"])) {

        $actor = $_GET["db"];
        $time = $_GET["time"];

        if ($meta == "") {

            $query = "SELECT ACTORS.META, ACTORS.NAME AS ACTOR_NAME, OVERLAYS.*, ACTORS.ACTOR_ID AS ACTOR_ID_ALT, ASSETS.*, OVERLAY_POINTS.* FROM ACTORS INNER JOIN ASSETS ON ASSETS.ASSET_ID = ACTORS.ASSET_ID LEFT JOIN OVERLAYS ON OVERLAYS.ACTOR_ID = ACTORS.ACTOR_ID LEFT JOIN OVERLAY_POINTS ON OVERLAY_POINTS.OVERLAY_ID = OVERLAYS.OVERLAY_ID WHERE ACTORS.SESSION = '$session' AND (ASSETS.ASSET_TYPE_ID = 1 OR ASSETS.ASSET_TYPE_ID = 2) AND ACTORS.ACTOR_ID = $actor AND `TIME` = $time AND (ACTORS.META IS NULL OR ACTORS.META = '') AND ACTORS.TAG IS NULL ORDER BY ACTORS.ACTOR_ID ASC";


        } else {

            $query = "SELECT ACTORS.META, ACTORS.NAME AS ACTOR_NAME, OVERLAYS.*, ACTORS.ACTOR_ID AS ACTOR_ID_ALT, ASSETS.*, OVERLAY_POINTS.* FROM ACTORS INNER JOIN ASSETS ON ASSETS.ASSET_ID = ACTORS.ASSET_ID LEFT JOIN OVERLAYS ON OVERLAYS.ACTOR_ID = ACTORS.ACTOR_ID LEFT JOIN OVERLAY_POINTS ON OVERLAY_POINTS.OVERLAY_ID = OVERLAYS.OVERLAY_ID WHERE ACTORS.SESSION = '$session' AND (ASSETS.ASSET_TYPE_ID = 1 OR ASSETS.ASSET_TYPE_ID = 2) AND ACTORS.ACTOR_ID = $actor AND `TIME` = $time AND ACTORS.META = '$meta' AND ACTORS.TAG IS NULL ORDER BY ACTORS.ACTOR_ID ASC";

        }

    } else if (isset($_GET["db"])) {

        $actor = $_GET["db"];
        $time = $_GET["time"];

        if ($meta == "") {

            $query = "SELECT ACTORS.META, ACTORS.NAME AS ACTOR_NAME, OVERLAYS.*, ACTORS.ACTOR_ID AS ACTOR_ID_ALT, ASSETS.*, OVERLAY_POINTS.* FROM ACTORS INNER JOIN ASSETS ON ASSETS.ASSET_ID = ACTORS.ASSET_ID LEFT JOIN OVERLAYS ON OVERLAYS.ACTOR_ID = ACTORS.ACTOR_ID LEFT JOIN OVERLAY_POINTS ON OVERLAY_POINTS.OVERLAY_ID = OVERLAYS.OVERLAY_ID WHERE ACTORS.SESSION = '$session' AND (ASSETS.ASSET_TYPE_ID = 1 OR ASSETS.ASSET_TYPE_ID = 2) AND ACTORS.ACTOR_ID = $actor AND (ACTORS.META IS NULL OR ACTORS.META = '') AND ACTORS.TAG IS NULL ORDER BY ACTORS.ACTOR_ID ASC";


        } else {

            $query = "SELECT ACTORS.META, ACTORS.NAME AS ACTOR_NAME, OVERLAYS.*, ACTORS.ACTOR_ID AS ACTOR_ID_ALT, ASSETS.*, OVERLAY_POINTS.* FROM ACTORS INNER JOIN ASSETS ON ASSETS.ASSET_ID = ACTORS.ASSET_ID LEFT JOIN OVERLAYS ON OVERLAYS.ACTOR_ID = ACTORS.ACTOR_ID LEFT JOIN OVERLAY_POINTS ON OVERLAY_POINTS.OVERLAY_ID = OVERLAYS.OVERLAY_ID WHERE ACTORS.SESSION = '$session' AND (ASSETS.ASSET_TYPE_ID = 1 OR ASSETS.ASSET_TYPE_ID = 2) AND ACTORS.ACTOR_ID = $actor AND ACTORS.META = '$meta' AND ACTORS.TAG IS NULL  ORDER BY ACTORS.ACTOR_ID ASC";

        }


    } else {

        if ($meta == "") {

            $query = "SELECT ACTORS.META, ACTORS.NAME AS ACTOR_NAME, OVERLAYS.*, ACTORS.ACTOR_ID AS ACTOR_ID_ALT, ASSETS.*, OVERLAY_POINTS.* FROM ACTORS INNER JOIN ASSETS ON ASSETS.ASSET_ID = ACTORS.ASSET_ID LEFT JOIN OVERLAYS ON OVERLAYS.ACTOR_ID = ACTORS.ACTOR_ID LEFT JOIN OVERLAY_POINTS ON OVERLAY_POINTS.OVERLAY_ID = OVERLAYS.OVERLAY_ID WHERE ACTORS.SESSION = '$session' AND (ASSETS.ASSET_TYPE_ID = 1 OR ASSETS.ASSET_TYPE_ID = 2) AND (ACTORS.META IS NULL OR ACTORS.META = '') AND ACTORS.TAG IS NULL ORDER BY ACTORS.ACTOR_ID ASC";


        } else {

            $query = "SELECT ACTORS.META, ACTORS.NAME AS ACTOR_NAME, OVERLAYS.*, ACTORS.ACTOR_ID AS ACTOR_ID_ALT, ASSETS.*, OVERLAY_POINTS.* FROM ACTORS INNER JOIN ASSETS ON ASSETS.ASSET_ID = ACTORS.ASSET_ID LEFT JOIN OVERLAYS ON OVERLAYS.ACTOR_ID = ACTORS.ACTOR_ID LEFT JOIN OVERLAY_POINTS ON OVERLAY_POINTS.OVERLAY_ID = OVERLAYS.OVERLAY_ID WHERE ACTORS.SESSION = '$session' AND (ASSETS.ASSET_TYPE_ID = 1 OR ASSETS.ASSET_TYPE_ID = 2) AND ACTORS.META = '$meta' AND ACTORS.TAG IS NULL ORDER BY ACTORS.ACTOR_ID ASC";


        }

    }

	$result = $conn->query($query);

    while ($row = $result->fetch_object()){


        $output[$row->ACTOR_ID_ALT]["data"] = $row;

        if (!isset($output[$row->ACTOR_ID_ALT]["overlays"])) {

        	$output[$row->ACTOR_ID_ALT]["overlays"] = array();

        }


        if (!isset($output[$row->ACTOR_ID_ALT]["tweens"])) {

            $output[$row->ACTOR_ID_ALT]["tweens"] = array();

        }        

        if ($row->TIME != null) {

	        $output[$row->ACTOR_ID_ALT]["overlays"][$row->OVERLAY_ID]["data"] = $row;
	        $output[$row->ACTOR_ID_ALT]["overlays"][$row->OVERLAY_ID]["points"][] = array(
                "db" => $row->OVERLAY_POINT_ID,
	        	"hide" => $row->HIDE,
	        	"position" => array($row->X, $row->Y)
        	);

        }

    }



    $query = "SELECT INTERACTION_ID, `ORDER`, A0.NAME AS ACTOR_NAME_0, A1.NAME AS ACTOR_NAME_1, DESCRIPTION, ACTOR_ID_0, ACTOR_ID_1, DIRECTION, LENGTH
FROM INTERACTIONS
LEFT JOIN ACTORS A0
ON INTERACTIONS.ACTOR_ID_0 = A0.ACTOR_ID
LEFT JOIN ACTORS A1
ON INTERACTIONS.ACTOR_ID_1 = A1.ACTOR_ID
WHERE TYPE = 4 AND (A0.SESSION = '$session' OR A1.SESSION = '$session')
ORDER BY `ORDER` ASC";
    $result = $conn->query($query);

    while ($row = $result->fetch_object()){

        if (isset($output[$row->ACTOR_ID_0]["tweens"])) {

            // $output[$row->ACTOR_ID_0]["tweens"] = array();
            $output[$row->ACTOR_ID_0]["tweens"][$row->INTERACTION_ID]["data"] = $row;

        }


    }



    $result->close();




    echo json_encode($output);	

?>